import random
import discord


trivt_list = {
    1: {"question": "Which of the four lords in *Resident Evil: Village* is the most dangerous according to The Duke?", 
    "ans1": "Alcina Dimitrescu", "ans2": "Donna Beneviento", "ans3": "Salvatore Moreau", "ans4": "Karl Heisenberg", "answer": "4"},
    2: {"question": "In *Resident Evil 6*, which final boss does the player encounter in Chris Redfield's campaign?", 
    "ans1": "Derek C. Simmons", "ans2": "HAOS", "ans3": "Ustanak", "ans4": "Albert Wesker", "answer": "2"},
    3: {"question": "In *Undertale*, who was Flowey prior to becoming a flower?", 
    "ans1": "Asriel Dreemurr", "ans2": "Alphys", "ans3": "Asgore Dreemurr", "ans4": "Sans", "answer": "1"},
    4: {"question": "Which two characters were turned into stone statues in Chapter 2 of *Deltarune*?", 
    "ans1": "Susie and Kris", "ans2": "Lancer and Rouxls Kaard", "ans3": "King and Queen", "ans4": "Noelle and Berdly", "answer": "2"},
    5: {"question": "What is the name of the patient the player usually operates on in *Surgeon Simulator*?", 
    "ans1": "Bob", "ans2": "Nigel", "ans3": "Kurt", "ans4": "Madison", "answer": "1"},
    6: {"question": "In *Tom Clancy's Rainbow Six Siege*, which operator CANNOT use the M870 Shotgun?", 
    "ans1": "Bandit", "ans2": "Recruit (Defense)", "ans3": "Kapkan", "ans4": "Jäger", "answer": "3"},
    7: {"question": "How many bits are there in a byte?", 
    "ans1": "4 bits", "ans2": "8 bits", "ans3": "32 bits", "ans4": "64 bits", "answer": "2"},
    8: {"question": "Which of the following is a cryptographic hash function?", 
    "ans1": "MD5", "ans2": "DSS", "ans3": "RSA", "ans4": "SHA", "answer": "4"},
    9: {"question": "Which of the following weapons can you aim down sights (ADS) with in *Counter Strike: Global Offensive*?", 
    "ans1": "Negev", "ans2": "SCAR-20", "ans3": "P90", "ans4": "M249", "answer": "2"},
    10: {"question": "Which of the following prisons is NOT a Transport Prison in *The Escapists 2*?", 
    "ans1": "Cougar Creek Railroad", "ans2": "H.M.S Orca", "ans3": "Air Force Con", "ans4": "U.S.S Anomaly", "answer": "4"},
    11: {"question": "What is Fool's Gold also known as?", 
    "ans1": "Ferrite", "ans2": "Granite", "ans3": "Pyrite", "ans4": "Aurite", "answer": "3"},
    12: {"question": "Which of the following elements is a halogen?", 
    "ans1": "Oxygen", "ans2": "Astatine", "ans3": "Strontium", "ans4": "Tungsten", "answer": "2"},
    13: {"question": "In *PlanetSide 2*, which Lightning tank cannon is capable of killing standard infantry using flak armour with a single direct hit?", 
    "ans1": "L100 Python AP", "ans2": "L100 Python HEAT", "ans3": "L100 Python HESH", "ans4": "C75 Viper", "answer": "3"},
    14: {"question": "Which of the following is NOT a sidearm in *Tom Clancy's Rainbow Six Siege*?", 
    "ans1": "P10 RONI", "ans2": "P12", "ans3": "SDP 9mm", "ans4": "SMG-11", "answer": "1"},
    15: {"question": "What is the term used when referring to the production and behaviour of materials at very low temperatures?", 
    "ans1": "Cryonics", "ans2": "Cryostasis", "ans3": "Cryoablation", "ans4": "Cryogenics", "answer": "4"},
    16: {"question": "\"Lesion\" Liu Tze Long appears in *Tom Clacncy's Ghost Recon* as mission control under a call sign. What is this call sign?", 
    "ans1": "Overlord", "ans2": "R6 Actual", "ans3": "Rainbow Six", "ans4": "Lesion", "answer": "2"},
    17: {"question": "Which of the following titles did the Roman general Gaius Julius Caesar NOT hold?", 
    "ans1": "Dictator", "ans2": "Princeps Senatus", "ans3": "Pontifex Maximus", "ans4": "Imperator", "answer": "2"},
    18: {"question": "The Spyglass in *Minecraft* reduces your FOV by a certain percentage when used. What is this percentage reduction?", 
    "ans1": "50%", "ans2": "70%", "ans3": "90%", "ans4": "100%", "answer": "3"},
    19: {"question": "What is the arming distance of grenades fired from standard Underbarrel Grenade, Smoke, and Incendiary Launchers in *PlanetSide 2*?", 
    "ans1": "5 metres", "ans2": "10 metres", "ans3": "15 metres", "ans4": "There is no arming distance", "answer": "2"},
    20: {"question": "Which of the following is the Heavy Assault's Adaptive Class Underbarrel grenade type in *PlanetSide 2*?", 
    "ans1": "Havoc Grenades", "ans2": "Concussion Grenades", "ans3": "Impulse Grenades", "ans4": "Fragmentation Grenades", "answer": "1"},
    21: {"question": "In *PlanetSide 2*, how much damage can a Nanite Mesh Generator overshield absorb before failing?", 
    "ans1": "300", "ans2": "350", "ans3": "400", "ans4": "450", "answer": "4"},
    22: {"question": "In *Tom Clancy's Rainbow Six Siege*, the following shotguns are pump-action EXCEPT for:", 
    "ans1": "M590A1", "ans2": "Supernova", "ans3": "FO-12", "ans4": "ITA12L", "answer": "3"},
    23: {"question": "Which of the following operators have access to 3 primary weapon choices in *Tom Clancy's Rainbow Six Siege*?", 
    "ans1": "Tachanka", "ans2": "Mozzie", "ans3": "Blackbeard", "ans4": "Fuze", "answer": "4"},
    24: {"question": "In *Tom Clancy's Rainbow Six Siege*, the following Attacking operators have access to Ballistic Shields EXCEPT for:", 
    "ans1": "Blitz", "ans2": "Blackbeard", "ans3": "Montagne", "ans4": "Fuze", "answer": "2"},
    25: {"question": "Which of these words holds the definition \"stubbornly refusing to change one's opinion or chosen course of action in spite of persuation\"?", 
    "ans1": "Cantankerous", "ans2": "Crotchety", "ans3": "Obstinate", "ans4": "Iniquitous", "answer": "3"},
    26: {"question": "In *PlanetSide 2*, which of these empire-specific sniper rifles does not come pre-mounted with a scope?", 
    "ans1": "AF-8 RailJack", "ans2": "TRAP-M1", "ans3": "Phaseshift VX-S", "ans4": "ADVX // Mako", "answer": "2"},
    27: {"question": "In *Tom Clancy's Rainbow Six Siege*, how much health can Doc's MPD-0 Stim Pistol restore to an operator NOT in DBNO?", 
    "ans1": "40HP", "ans2": "45HP", "ans3": "50HP", "ans4": "55HP", "answer": "1"},
    28: {"question": "In *Phasmophobia*, which ghost type decreases its activity when players stay together?", 
    "ans1": "Revenant", "ans2": "Yurei", "ans3": "Shade", "ans4": "Demon", "answer": "3"},
    29: {"question": "Which of the following sidearms in *Tom Clancy's Rainbow Six Siege* features a green laser sight?", 
    "ans1": "P226 Mk 25", "ans2": "5.7 USG", "ans3": "P-10C", "ans4": "RG15", "answer": "4"},
    30: {"question": "What does the CAMRS in *Tom Clancy's Rainbow Six Siege* stand for?", 
    "ans1": "Canadian Advanced Mil-dot Reticle Standard", "ans2": "Canadian Army Marksman Rifle System", "ans3": "Canadian Advanced Marksman Rifle System", "ans4": "Customizable Anti Material Rifle System", "answer": "2"},
    31: {"question": "What is the real life counterpart of the .357 Keratos in *Tom Clancy's Rainbow Six Siege*?", 
    "ans1": "Taurus Judge", "ans2": "S&W Model 586", "ans3": "Chiappa Rhino", "ans4": "Colt Python", "answer": "3"},
    32: {"question": "In *PlanetSide 2*, which of the following is part of the Terran Republic's \"Trident\" arsenal?", 
    "ans1": "MGR-A1 Vanquisher", "ans2": "MG-H1 Watchman", "ans3": "VE-S Canis", "ans4": "NS-44L Blackhand", "answer": "2"},
    33: {"question": "In *PlanetSide 2*, which of the following is NOT an IRNV (night vision) optic?", 
    "ans1": "DV6", "ans2": "Nx1", "ans3": "HS/NV Scope", "ans4": "NiCO", "answer": "4"},
    34: {"question": "In *PlanetSide 2*, which of the following is a Nanite Systems optic?", 
    "ans1": "TSO-1", "ans2": "Rx1", "ans3": "Corona IR", "ans4": "CCLR", "answer": "4"},
    35: {"question": "In *Tom Clancy's Rainbow Six Siege*, which of the following optic magnifications does NOT exist?", 
    "ans1": "x4.0", "ans2": "x5.0", "ans3": "x8.0", "ans4": "x12.0", "answer": "3"},
    36: {"question": "In the Nekopara series, which of the following characters is Kashou's grandmother?", 
    "ans1": "Azuki", "ans2": "Beignet", "ans3": "Maple", "ans4": "Shigure", "answer": "2"},
    37: {"question": "In the Nekopara series, which of the following breeds of cat is Fraise?", 
    "ans1": "Scottish Curl", "ans2": "Maine Coon", "ans3": "Chinchilla Persian", "ans4": "Munchkin", "answer": "3"},
    38: {"question": "In *PlanetSide 2*, which of the following damage types does the M18 Needler use?", 
    "ans1": "Air to Ground Warheads", "ans2": "Small Arms", "ans3": "Infantry Rocket Launchers", "ans4": "Aircraft Machine Guns", "answer": "4"},
    39: {"question": "In *PlanetSide 2*, what is the frontal damage mitigation provided by the Forward Vanguard Shield?", 
    "ans1": "20%", "ans2": "34%", "ans3": "67%", "ans4": "88%", "answer": "3"},
    40: {"question": "All tanks in *PlanetSide 2* sport one single barrel, with the exception of the:", 
    "ans1": "Vanguard", "ans2": "Prowler", "ans3": "Magrider", "ans4": "Colossus", "answer": "2"},
    41: {"question": "Which of the following vehicles in *PlanetSide 2* CANNOT be pulled without spending nanites?", 
    "ans1": "Sunderer", "ans2": "ANT", "ans3": "Liberator", "ans4": "Flash", "answer": "3"},
    42: {"question": "In *PlanetSide 2*, which of the following Reaver nose cannons is exclusive to Interceptor variants?", 
    "ans1": "M20 Kestrel", "ans2": "M20-W Appaloosa", "ans3": "Vortek Rotary", "ans4": "M20 Mustang", "answer": "2"},
    43: {"question": "In *PlanetSide 2*, which of the following weapons is capable of dealing flak damage?", 
    "ans1": "G40-F Ranger", "ans2": "Titan-150 AP", "ans3": "M4-F Pillager", "ans4": "L105 Zephyr", "answer": "1"},
    44: {"question": "In *PlanetSide 2*, which of the following Flash primary weapons is a common pool weapon?", 
    "ans1": "M4-F Pillager", "ans2": "LA7 Buzzard", "ans3": "V30-F Starfall", "ans4": "M12 Kobalt-F", "answer": "4"},
    45: {"question": "Which of the following melee weapons in *PlanetSide 2* can be powered to deal additional damage?", 
    "ans1": "NSX Amaterasu", "ans2": "Chainblade", "ans3": "Carver", "ans4": "Damascus Edge", "answer": "3"},
    46: {"question": "In the Call of Duty: Zombies storyline, who was responsible for poisoning the drinks of the Primis and Ultimis crews?", 
    "ans1": "Primis Richtofen", "ans2": "Primis Nikolai", "ans3": "Primis Takeo", "ans4": "Ultimis Nikolai", "answer": "2"},
    47: {"question": "In *Dead Frontier 2*, which of the following effects does the Paramedic's Bag NOT cleanse?", 
    "ans1": "Severe Burns", "ans2": "Radiation Poisoning", "ans3": "Bacterial Infection", "ans4": "Bleeding", "answer": "2"},
    48: {"question": "In *Dead Frontier 2*, which of the following effects is NOT an Intoxicated effect?", 
    "ans1": "-20% Maximum Accuracay", "ans2": "-5% Incoming Damage", "ans3": "-20% Minimum Accuracy", "ans4": "-10% Aim Speed", "answer": "4"},
    49: {"question": "Which of the following is the smallest map in *PlayerUnknown's Battlegrounds*?", 
    "ans1": "Haven", "ans2": "Taego", "ans3": "Paramo", "ans4": "Karakin", "answer": "1"}, 
    50: {"question": "Which of the following potions in *Minecraft* is brewed with an Awkward Potion, Golden Carrot, and Fermented Spider Eye?", 
    "ans1": "Potion of Night Vision", "ans2": "Potion of Blindness", "ans3": "Potion of Invisibility", "ans4": "None of the above", "answer": "3"},
    51: {"question": "Of all lethal sidearms in *Ready or Not*, which one of them can be equipped with an IR Laser?", 
    "ans1": "57 USG", "ans2": ".357 Magnum", "ans3": "USP45", "ans4": "P92X", "answer": "3"},
    52: {"question": "Which of the following is NOT a headgear option in *Ready or Not*?", 
    "ans1": "Anti-Flash Goggles", "ans2": "Ballistic Mask", "ans3": "NVGS", "ans4": "Fire-Retardant Mask", "answer": "4"},
    53: {"question": "Which mission mode in *Ready or Not* has a difficulty rating of Insane?", 
    "ans1": "Raid", "ans2": "Hostage Rescue", "ans3": "Active Shooter", "ans4": "Barricaded Suspects", "answer": "2"},
    54: {"question": "Which of the following is NOT an armour level in *Ready or Not*? ", 
    "ans1": "No Armour", "ans2": "Light Armour", "ans3": "Medium Armour", "ans4": "Heavy Armour", "answer": "3"},
    55: {"question": "In the anime *The Idolm@ster*, which idol's story did Episode 21 \"Promise\" focus on?", 
    "ans1": "Kisaragi Chihaya", "ans2": "Minase Iori", "ans3": "Haruka Amami", "ans4": "Futami Ami", "answer": "1"},
    56: {"question": "What is the fastest ground vehicle in *PlanetSide 2*?", 
    "ans1": "Flash", "ans2": "Harasser", "ans3": "Sunderer", "ans4": "Lightning", "answer": "2"},
    57: {"question": "In *PlanetSide 2*, what type of vehicle CANNOT be pulled from the Flotillas on Oshur?", 
    "ans1": "Light Vehicles", "ans2": "Support Vehicles", "ans3": "Mobile Armour", "ans4": "Heavy Aircraft", "answer": "3"},
    58: {"question": "In *PlanetSide 2*, Exodus PPCs can be found on the Flotillas on Oshur. What does \"PPC\" stand for?", 
    "ans1": "Pulsed Particle Cannon", "ans2": "Particle Projection Cannon", "ans3": "Personnel Protection Convoy", "ans4": "Polystellarite Preparation Canister", "answer": "2"},
    59: {"question": "In *PlanetSide 2*, which of the following Terran Republic weapons can equip KCAP Ammunition?", 
    "ans1": "T1S Cycler", "ans2": "TMG-50", "ans3": "MG-S1 Jackal", "ans4": "AMR-66", "answer": "3"},
    60: {"question": "In *PlanetSide 2*, which of the following is a fully automatic shotgun?", 
    "ans1": "LA39 Bruiser", "ans2": "FA1 Barrage", "ans3": "Pandora VX25", "ans4": "HSG-400", "answer": "3"},
    61: {"question": "In *Ready or Not*, which of the following devices CANNOT unlock a locked door?", 
    "ans1": "Lockpick Gun", "ans2": "Multitool", "ans3": "C2 Charge", "ans4": "Door Wedge", "answer": "4"},
    62: {"question": "In *Ready or Not*, What ammunition does the M32A1 Launcher fire?", 
    "ans1": "Flash", "ans2": "CS Gas", "ans3": "Stinger", "ans4": "Fragmentation", "answer": "1"},
    63: {"question": "In the anime series *My Teen Romantic Comedy SNAFU*, what is the first name of Hikigaya's sister?", 
    "ans1": "Yui", "ans2": "Yukino", "ans3": "Komachi", "ans4": "Iroha", "answer": "3"},
    64: {"question": "In the *Nekopara* anime series, what name did the nameless stray catgirl receive?",
    "ans1": "Sugarcane", "ans2": "Fraise", "ans3": "Cacao", "ans4": "Milk", "answer": "3"},
    65: {"question": "In *Hell Let Loose*, which faction uses Morphine Ampoules to revive downed soldiers?", 
    "ans1": "United States", "ans2": "Germany", "ans3": "Soviet Union", "ans4": "All of the above", "answer": "2"},
    66: {"question": "In *Hell Let Loose*, which of the following tanks lacks a driver-controlled hull machine gun?", 
    "ans1": "Sherman M4A1", "ans2": "IS-1", "ans3": "Luchs", "ans4": "Stuart", "answer": "3"},
    67: {"question": "In *Hell Let Loose*, which of the following spawn options features the longest wave timer?", 
    "ans1": "Outposts", "ans2": "Garrisons", "ans3": "Half Tracks", "ans4": "Airheads", "answer": "3"},
    68: {"question": "In *Hell Let Loose*, which of the following weapons is NOT a standard issue Machine Gunner weapon?", 
    "ans1": "Browning M1919", "ans2": "MG34", "ans3": "MG42", "ans4": "DP-27", "answer": "3"},
    69: {"question": "In *Hell Let Loose*, what weapon does the United States \"Corpsman\" Medic class use?", 
    "ans1": "M1 Garand", "ans2": "M1 Carbine", "ans3": "M3 Grease Gun", "ans4": "Colt M1911", "answer": "4"},
    70: {"question": "In *Hell Let Loose*, besides Officers, which other Infantry class can see markers from recon scans?", 
    "ans1": "Support", "ans2": "Engineer", "ans3": "Medic", "ans4": "Machine Gunner", "answer": "1"},
    71: {"question": "In *Hell Let Loose*, which faction's standard Assault uses a semi-auto rifle instead of an SMG?", 
    "ans1": "United States", "ans2": "Germany", "ans3": "Soviet Union", "ans4": "None of the above", "answer": "2"},
    72: {"question": "In *Hell Let Loose*, how many Bunker blueprints can an Engineer place at any given time?", 
    "ans1": "1", "ans2": "2", "ans3": "3", "ans4": "4", "answer": "1"},
    73: {"question": "In *PlanetSide 2*, what benefit does the Angled Forward Grip provide?", 
    "ans1": "-60% First shot recoil", "ans2": "-20% ADS bloom", "ans3": "-25% Vertical recoil", "ans4": "-25% Horizontal recoil", "answer": "1"},
    74: {"question": "In *PlanetSide 2*, what benefit does the Mobile Prediction Laser provide?", 
    "ans1": "+33% Hipfire accuracy", "ans2": "-20% ADS bloom", "ans3": "-60% Hipfire horizontal & vertical recoil", "ans4": "-40% Hipfire bloom", "answer": "3"},
    75: {"question": "In *PlanetSide 2*, which of the following is NOT a Chimera main cannon?", 
    "ans1": "CT-102 Satyr", "ans2": "CT-120 Squash Head", "ans3": "CT-135", "ans4": "CT-150 Cyclops", "answer": "2"},
    76: {"question": "In *PlanetSide 2*, which empire-specific Basilisk deals the highest damage per shot?", 
    "ans1": "N30 Trawler", "ans2": "M18 Palisade", "ans3": "V42 Pariah", "ans4": "CT2-20 HCG", "answer": "1"},
    77: {"question": "In *PlanetSide 2*, which of the following TR scout rifles CANNOT be equipped with explosive ammo?", 
    "ans1": "MG-HBR1 Dragoon", "ans2": "HSR-1", "ans3": "SOAS-20", "ans4": "DMR-99", "answer": "3"},
    78: {"question": "In *Tom Clancy's Rainbow Six Vegas 2*, under which A.C.E.S branch is the Shield unlocked?", 
    "ans1": "Marksman", "ans2": "Assault", "ans3": "CQB", "ans4": "The Shield is unlocked by default", "answer": "2"},

    700: {"question": "", "ans1": "", "ans2": "", "ans3": "", "ans4": "", "answer": ""},
}


def colRan():
    r = random.randint(0,255)
    g = random.randint(0,255)
    b= random.randint(0,255)
    colour=discord.Colour.from_rgb(r, g, b)
    return colour


cmdWhitelist = [
    521293177315917850,
    591074600411070502,
    "WhatTheVeggies#1197",
    "Krygswyrfer#8394",
    "<@!521293177315917850>",
    "<@!591074600411070502>",
]


planetguns = [
    "T1 Cycler", "T1S Cycler", "T1B Cycler", "Cycler TRV", "MG-A1 Arbalest", "TORQ-9", "SABR-13", "TAR", "T1A Unity",
    "TRAC-5", "TRAC-5 S", "TRAC-5 Burst", "LC2 Lynx", "LC3 Jaguar", "HC1 Cougar", "MG-C1 Kindred", "T5 AMC", "TRAC-Shot",
    "M77-B", "SR-7", "TSAR-42", "RAMS .50M", "99SV", "KSR-35", "TRAP-M1", "Bighorn .50M",
    "AMR-66", "SOAS-20", "HSR-1", "MG-HBR1 Dragoon", "DMR-99",
    "T9 CARVV", "T9 CARV-S", "T16 Rhino", "T32 Bull", "TMG-50", "MSW-R", "MG-H1 Watchman", "T9A Butcher",
    "AS16 NightHawk", "FA1 Barrage", "TRS-12 Uppercut", "TAS-16 Blackjack", "TS4 Haymaker", "Havoc",
    "SMG-46 Armistice", "PDW-16 Hailstorm", "MG-S1 Jackal", "Shuriken",
    "TX1 Repeater", "TX2 Emperor", "TS2 Inquisitor", "T4 AMP", "The President",
    "ML-7", "ASP-30 Grounder", "M9 SKEP Launcher", "T2 Striker",
    "T7 Mini-Chaingun",
    "Chainblade", "Ripper", "Hexedge", "Auraxium Chainblade",
    "M1 Heavy Cycler", "M2 Mutilator", "M6 Onslaught", "MRC3 Mercy", "MR1 Fracture", "M3 Pounder HEG",

    "GR-22", "NC1 Gauss Rifle", "Gauss Rifle Burst", "Gauss Rifle S", "Reaper DMR", "Carnage AR", "NC-9 A-Tross", "MGR-A1 Vanquisher", "Gauss Prime",
    "AF-19 Mercenary", "GD-7F", "AC-X11", "Gauss Compact Burst", "Gauss Compact S", "Razor GD-23", "AF-4A Bandit", "MGR-C1 Charger", "19AA Fortuna",
    "EM1", "EM6", "GD-22S", "NC6 Gauss SAW", "NC6S Gauss SAW", "LA1 Anchor", "MGR-L1 Promise", "NC6A GODSAW",
    "AF-6 Shadow", "AF-18 Stalker", "Warden", "MGR-M1 Bishop", "GD Guardian",
    "Mauler S6", "AF-57 Piston", "NC12 Sweeper", "GD-66 Claw", "LA39 Bruiser", "The Brawler",
    "Gauss SPR", "Impetus", "LA80", "NC14 Bolt Driver", "SAS-R", "EM4 Longshot", "AF-8 RailJack", "The Moonshot"
    "AF-4 Cyclone", "Blitz GD-10", "MGR-S1 Gladius", "Tempest",
    "NC4 Mag-Shot", "LA8 Rebel", "LA3 Desperado", "NC08 Mag-Scatter", "The Executive",
    "Mag-Cutter", "Carver", "Hardlight Dagger", "Auraxium Mag-Cutter",
    "Shrike", "AF-22 Crow", "Hawk GD-68", "NC15 Phoenix",
    "NC05 Jackhammer",
    "AF-23 Grinder", "AF-34 Mattock", "AF-41 Hacksaw", "NCM1 Scattercannon", "NCM2 Falcon", "NCM3 Raven",

    "CME", "Equinox VE2", "Equinox VE2 Burst", "Pulsar VS1", "H-V45", "Corvus VA55", "Terminus VX-9", "VE-A Lacerta", "Darkstar",
    "Solstice VE3", "Pulsar C", "Solstice Burst", "Solstice SF", "VX6-7", "Serpent VE92", "Zenith VX-5", "VE-C Horizon", "Eclipse VE3A"
    "Lasher X2",
    "Flare VE6", "Orion VS54", "Pulsar LSW", "SVA-88", "VX29 Polaris", "Ursa", "VE-H MAW", "Betelgeuse 54-A",
    "Force-Blade", "Lumine Edge", "Damascus Edge", "Auuraxium Force-Blade",
    "S1", "Hades VSH4", "Nemesis VSH9", "Lancer VS22",
    "Artemis VX26", "Nyx VX31", "Eidolon VE33", "VE-LR Obelisk", "Revenant"
    "Beamer VS3", "Manticore SX40", "Cerberus", "Spiker", "The Immortal",
    "Nova", "Pandora VX25", "Thanatos VE70", "Phobos VX86", "Deimos VA29", "Chaos",
    "Ghost", "Phantom VA23", "V10", "VA39 Spectre", "XM98", "Parallax VX3", "Phaseshift VX-S", "Parsec VX3-A",
    "Eridani SX5", "Sirius SX12", "VE-S Canis", "Skorpios",
    "Blueshift VM5", "Cosmos VM3", "Nebula VM20", "Quasar VM1", "Comet VM2", "Vortex VM21",

    "AR-100", "AR-101", "AR-N203", "AR-ARX Maxwell",
    "CB-100", "CB-200", "CB-X75", "CB-ARX Newton",
    "XMG-100", "XMG-155", "XMG-200", "XMG-ARX Galilei",
    "NS Commando", "NS-A Commando",
    "LAV-AG", "LAV-LG", "LAV-LA",
    "BAR-100", "BAR-200", "BAR-A75", "BAR-ARX Feynman",
    "HSG-400", "SG-100", "SG-A25", "SG-ARX Rutherford",
    "U-100 Lastly", "U-150 Recall", "U-200 Harbinger", "U-ARX Dirac",
    "ADVX // Mako", "SR-100", "SR-150", "SR-L75", "SR-ARX Einstein",
    "PMG-100", "PMG-200", "PMG-3XB", "PMG-ARX Schrodinger",
    "Grenade Printer", "D7 Hummingbird", "D11 Detonator",

    "NS-11A", "NSX-Yumi", "NSX-Kuwa,"
    "NS-11C", "NSX Tanto",
    "Seeker HLX", "NS-03 Thumper", "SPRK-33's Stomper",
    "NS-15M2", "NSX Naginata",
    "NSX Amaterasu", "NS Campion", "NS Harrower", "NS-W Survivor", "Ancient Psykinetic Blade", "NS-Firebug",
    "NS AutoBlade", 'NS-TMC-01 "His Regards"', "NS Icebreaker", "The Slasher", "Icikill", "Fatestealer", "Nightshade", "Excursion Kukri", "NS-W Survivor",
    "NS Annihilator", "NS Decimator", "NS Scorpion", "NS-R3 Swarm", "NSX Masamune", "NSX Muramasa", "The Kraken", "Rocklet Rifle",
    "NS-30 Vandal", "NSX Tomoe", "NS-30 Tranquility", "NSX Sesshin",
    "NS-357 Underboss", "NS-44 Commissioner", "NS-44L Blackhand", "NS-45 Pilot", "NS-61 Emissary", "Hunter QCX",
    "NS-357 IA", "NS-44L Showdown", "NSX Yawara",
    "NS Deep Freeze", "NS CandyCannon 3000", "TR Patriot Flare Gun", "NC Patriot Flare Gun", "VS Patriot Flare Gun", "NS Patriot Flare Gun",
    "TR Triumph Flare Gun", 'NC Triumph Flare Gun', "VS Triumph Flare Gun",
    "NS Baron G5", "NS Viscount G6", "NSX Daimyo", "NS-AM7 Archer", "NS-AM8 Shortbow",
    "NS-7 PDW", "MKV Suppressed", "NSX Tengu", "NS-66 Punisher", "NSX Kappa",
    "NS-10 Burster", "NS-20 Gorgon",
    "UBR-100 Frogman", "UBR-150 Sea Lion", "UBR-300 Swordfish", "UBP-1 Starfish",

    ]